---
- hosts: dev
  connection: ssh
  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: present

    - name: Start Apache Web Server
      service:
        name: httpd
        state: started

    - name: Ensure the /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Create the index.html file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add content to index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to the webserver</h1>
  
